package com.example.orm.model;

import java.util.Date;

public class MtBook {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.mt_book.book_id
	 * @mbg.generated  Wed Sep 18 15:30:38 ICT 2019
	 */
	private String bookId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.mt_book.book_title
	 * @mbg.generated  Wed Sep 18 15:30:38 ICT 2019
	 */
	private String bookTitle;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.mt_book.author_name
	 * @mbg.generated  Wed Sep 18 15:30:38 ICT 2019
	 */
	private String authorName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.mt_book.publisher
	 * @mbg.generated  Wed Sep 18 15:30:38 ICT 2019
	 */
	private String publisher;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.mt_book.publication_day
	 * @mbg.generated  Wed Sep 18 15:30:38 ICT 2019
	 */
	private java.sql.Date publicationDay;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.mt_book.insert_day
	 * @mbg.generated  Wed Sep 18 15:30:38 ICT 2019
	 */
	private Date insertDay;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.mt_book.update_day
	 * @mbg.generated  Wed Sep 18 15:30:38 ICT 2019
	 */
	private Date updateDay;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.mt_book.book_id
	 * @return  the value of public.mt_book.book_id
	 * @mbg.generated  Wed Sep 18 15:30:38 ICT 2019
	 */
	public String getBookId() {
		return bookId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.mt_book.book_id
	 * @param bookId  the value for public.mt_book.book_id
	 * @mbg.generated  Wed Sep 18 15:30:38 ICT 2019
	 */
	public void setBookId(String bookId) {
		this.bookId = bookId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.mt_book.book_title
	 * @return  the value of public.mt_book.book_title
	 * @mbg.generated  Wed Sep 18 15:30:38 ICT 2019
	 */
	public String getBookTitle() {
		return bookTitle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.mt_book.book_title
	 * @param bookTitle  the value for public.mt_book.book_title
	 * @mbg.generated  Wed Sep 18 15:30:38 ICT 2019
	 */
	public void setBookTitle(String bookTitle) {
		this.bookTitle = bookTitle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.mt_book.author_name
	 * @return  the value of public.mt_book.author_name
	 * @mbg.generated  Wed Sep 18 15:30:38 ICT 2019
	 */
	public String getAuthorName() {
		return authorName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.mt_book.author_name
	 * @param authorName  the value for public.mt_book.author_name
	 * @mbg.generated  Wed Sep 18 15:30:38 ICT 2019
	 */
	public void setAuthorName(String authorName) {
		this.authorName = authorName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.mt_book.publisher
	 * @return  the value of public.mt_book.publisher
	 * @mbg.generated  Wed Sep 18 15:30:38 ICT 2019
	 */
	public String getPublisher() {
		return publisher;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.mt_book.publisher
	 * @param publisher  the value for public.mt_book.publisher
	 * @mbg.generated  Wed Sep 18 15:30:38 ICT 2019
	 */
	public void setPublisher(String publisher) {
		this.publisher = publisher;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.mt_book.publication_day
	 * @return  the value of public.mt_book.publication_day
	 * @mbg.generated  Wed Sep 18 15:30:38 ICT 2019
	 */
	public java.sql.Date getPublicationDay() {
		return publicationDay;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.mt_book.publication_day
	 * @param publicationDay  the value for public.mt_book.publication_day
	 * @mbg.generated  Wed Sep 18 15:30:38 ICT 2019
	 */
	public void setPublicationDay(java.sql.Date publicationDay) {
		this.publicationDay = publicationDay;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.mt_book.insert_day
	 * @return  the value of public.mt_book.insert_day
	 * @mbg.generated  Wed Sep 18 15:30:38 ICT 2019
	 */
	public Date getInsertDay() {
		return insertDay;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.mt_book.insert_day
	 * @param insertDay  the value for public.mt_book.insert_day
	 * @mbg.generated  Wed Sep 18 15:30:38 ICT 2019
	 */
	public void setInsertDay(Date insertDay) {
		this.insertDay = insertDay;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.mt_book.update_day
	 * @return  the value of public.mt_book.update_day
	 * @mbg.generated  Wed Sep 18 15:30:38 ICT 2019
	 */
	public Date getUpdateDay() {
		return updateDay;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.mt_book.update_day
	 * @param updateDay  the value for public.mt_book.update_day
	 * @mbg.generated  Wed Sep 18 15:30:38 ICT 2019
	 */
	public void setUpdateDay(Date updateDay) {
		this.updateDay = updateDay;
	}

	public MtBook(String bookId, String bookTitle, String authorName, String publisher, java.sql.Date publicationDay,
			Date insertDay, Date updateDay) {
		super();
		this.bookId = bookId;
		this.bookTitle = bookTitle;
		this.authorName = authorName;
		this.publisher = publisher;
		this.publicationDay = publicationDay;
		this.insertDay = insertDay;
		this.updateDay = updateDay;
	}
	
	public MtBook(String bookId, String bookTitle, String authorName, String publisher, java.sql.Date publicationDay,
			Date insertDay) {
		super();
		this.bookId = bookId;
		this.bookTitle = bookTitle;
		this.authorName = authorName;
		this.publisher = publisher;
		this.publicationDay = publicationDay;
		this.insertDay = insertDay;
	}

	public MtBook(String bookId, String bookTitle, String authorName, String publisher, java.sql.Date publicationDay) {
		super();
		this.bookId = bookId;
		this.bookTitle = bookTitle;
		this.authorName = authorName;
		this.publisher = publisher;
		this.publicationDay = publicationDay;
	}

	public MtBook() {
	}
    
    
}