package com.example.orm.model;

import java.util.Date;

public class TblAdmin {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.tbl_admin.admin_id
	 * @mbg.generated  Thu Oct 31 17:03:11 ICT 2019
	 */
	private String adminId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.tbl_admin.password
	 * @mbg.generated  Thu Oct 31 17:03:11 ICT 2019
	 */
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.tbl_admin.admin_family_name
	 * @mbg.generated  Thu Oct 31 17:03:11 ICT 2019
	 */
	private String adminFamilyName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.tbl_admin.admin_fisrt_name
	 * @mbg.generated  Thu Oct 31 17:03:11 ICT 2019
	 */
	private String adminFisrtName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.tbl_admin.regist_id
	 * @mbg.generated  Thu Oct 31 17:03:11 ICT 2019
	 */
	private String registId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.tbl_admin.regist_date
	 * @mbg.generated  Thu Oct 31 17:03:11 ICT 2019
	 */
	private Date registDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.tbl_admin.update_id
	 * @mbg.generated  Thu Oct 31 17:03:11 ICT 2019
	 */
	private String updateId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.tbl_admin.update_date
	 * @mbg.generated  Thu Oct 31 17:03:11 ICT 2019
	 */
	private Date updateDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.tbl_admin.delete_flg
	 * @mbg.generated  Thu Oct 31 17:03:11 ICT 2019
	 */
	private String deleteFlg;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.tbl_admin.admin_id
	 * @return  the value of public.tbl_admin.admin_id
	 * @mbg.generated  Thu Oct 31 17:03:11 ICT 2019
	 */
	public String getAdminId() {
		return adminId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.tbl_admin.admin_id
	 * @param adminId  the value for public.tbl_admin.admin_id
	 * @mbg.generated  Thu Oct 31 17:03:11 ICT 2019
	 */
	public void setAdminId(String adminId) {
		this.adminId = adminId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.tbl_admin.password
	 * @return  the value of public.tbl_admin.password
	 * @mbg.generated  Thu Oct 31 17:03:11 ICT 2019
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.tbl_admin.password
	 * @param password  the value for public.tbl_admin.password
	 * @mbg.generated  Thu Oct 31 17:03:11 ICT 2019
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.tbl_admin.admin_family_name
	 * @return  the value of public.tbl_admin.admin_family_name
	 * @mbg.generated  Thu Oct 31 17:03:11 ICT 2019
	 */
	public String getAdminFamilyName() {
		return adminFamilyName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.tbl_admin.admin_family_name
	 * @param adminFamilyName  the value for public.tbl_admin.admin_family_name
	 * @mbg.generated  Thu Oct 31 17:03:11 ICT 2019
	 */
	public void setAdminFamilyName(String adminFamilyName) {
		this.adminFamilyName = adminFamilyName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.tbl_admin.admin_fisrt_name
	 * @return  the value of public.tbl_admin.admin_fisrt_name
	 * @mbg.generated  Thu Oct 31 17:03:11 ICT 2019
	 */
	public String getAdminFisrtName() {
		return adminFisrtName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.tbl_admin.admin_fisrt_name
	 * @param adminFisrtName  the value for public.tbl_admin.admin_fisrt_name
	 * @mbg.generated  Thu Oct 31 17:03:11 ICT 2019
	 */
	public void setAdminFisrtName(String adminFisrtName) {
		this.adminFisrtName = adminFisrtName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.tbl_admin.regist_id
	 * @return  the value of public.tbl_admin.regist_id
	 * @mbg.generated  Thu Oct 31 17:03:11 ICT 2019
	 */
	public String getRegistId() {
		return registId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.tbl_admin.regist_id
	 * @param registId  the value for public.tbl_admin.regist_id
	 * @mbg.generated  Thu Oct 31 17:03:11 ICT 2019
	 */
	public void setRegistId(String registId) {
		this.registId = registId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.tbl_admin.regist_date
	 * @return  the value of public.tbl_admin.regist_date
	 * @mbg.generated  Thu Oct 31 17:03:11 ICT 2019
	 */
	public Date getRegistDate() {
		return registDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.tbl_admin.regist_date
	 * @param registDate  the value for public.tbl_admin.regist_date
	 * @mbg.generated  Thu Oct 31 17:03:11 ICT 2019
	 */
	public void setRegistDate(Date registDate) {
		this.registDate = registDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.tbl_admin.update_id
	 * @return  the value of public.tbl_admin.update_id
	 * @mbg.generated  Thu Oct 31 17:03:11 ICT 2019
	 */
	public String getUpdateId() {
		return updateId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.tbl_admin.update_id
	 * @param updateId  the value for public.tbl_admin.update_id
	 * @mbg.generated  Thu Oct 31 17:03:11 ICT 2019
	 */
	public void setUpdateId(String updateId) {
		this.updateId = updateId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.tbl_admin.update_date
	 * @return  the value of public.tbl_admin.update_date
	 * @mbg.generated  Thu Oct 31 17:03:11 ICT 2019
	 */
	public Date getUpdateDate() {
		return updateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.tbl_admin.update_date
	 * @param updateDate  the value for public.tbl_admin.update_date
	 * @mbg.generated  Thu Oct 31 17:03:11 ICT 2019
	 */
	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.tbl_admin.delete_flg
	 * @return  the value of public.tbl_admin.delete_flg
	 * @mbg.generated  Thu Oct 31 17:03:11 ICT 2019
	 */
	public String getDeleteFlg() {
		return deleteFlg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.tbl_admin.delete_flg
	 * @param deleteFlg  the value for public.tbl_admin.delete_flg
	 * @mbg.generated  Thu Oct 31 17:03:11 ICT 2019
	 */
	public void setDeleteFlg(String deleteFlg) {
		this.deleteFlg = deleteFlg;
	}
}