package com.example.orm.model;

import java.sql.Date;

public class TblBook {
	
	public TblBook() {
	}
	
	public TblBook(String bookId, String bookTitle, String authorName, String publisher, Date publicationDay,
			String registId, java.util.Date date, String deleteFlg) {
		super();
		this.bookId = bookId;
		this.bookTitle = bookTitle;
		this.authorName = authorName;
		this.publisher = publisher;
		this.publicationDay = publicationDay;
		this.registId = registId;
		this.registDate = date;
		this.deleteFlg = deleteFlg;
	}



	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.tbl_book.book_id
	 * @mbg.generated  Thu Oct 31 17:03:11 ICT 2019
	 */
	private String bookId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.tbl_book.book_title
	 * @mbg.generated  Thu Oct 31 17:03:11 ICT 2019
	 */
	private String bookTitle;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.tbl_book.author_name
	 * @mbg.generated  Thu Oct 31 17:03:11 ICT 2019
	 */
	private String authorName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.tbl_book.publisher
	 * @mbg.generated  Thu Oct 31 17:03:11 ICT 2019
	 */
	private String publisher;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.tbl_book.publication_day
	 * @mbg.generated  Thu Oct 31 17:03:11 ICT 2019
	 */
	private Date publicationDay;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.tbl_book.regist_id
	 * @mbg.generated  Thu Oct 31 17:03:11 ICT 2019
	 */
	private String registId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.tbl_book.regist_date
	 * @mbg.generated  Thu Oct 31 17:03:11 ICT 2019
	 */
	private java.util.Date registDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.tbl_book.update_id
	 * @mbg.generated  Thu Oct 31 17:03:11 ICT 2019
	 */
	private String updateId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.tbl_book.update_date
	 * @mbg.generated  Thu Oct 31 17:03:11 ICT 2019
	 */
	private java.util.Date updateDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.tbl_book.delete_flg
	 * @mbg.generated  Thu Oct 31 17:03:11 ICT 2019
	 */
	private String deleteFlg;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.tbl_book.book_id
	 * @return  the value of public.tbl_book.book_id
	 * @mbg.generated  Thu Oct 31 17:03:11 ICT 2019
	 */
	public String getBookId() {
		return bookId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.tbl_book.book_id
	 * @param bookId  the value for public.tbl_book.book_id
	 * @mbg.generated  Thu Oct 31 17:03:11 ICT 2019
	 */
	public void setBookId(String bookId) {
		this.bookId = bookId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.tbl_book.book_title
	 * @return  the value of public.tbl_book.book_title
	 * @mbg.generated  Thu Oct 31 17:03:11 ICT 2019
	 */
	public String getBookTitle() {
		return bookTitle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.tbl_book.book_title
	 * @param bookTitle  the value for public.tbl_book.book_title
	 * @mbg.generated  Thu Oct 31 17:03:11 ICT 2019
	 */
	public void setBookTitle(String bookTitle) {
		this.bookTitle = bookTitle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.tbl_book.author_name
	 * @return  the value of public.tbl_book.author_name
	 * @mbg.generated  Thu Oct 31 17:03:11 ICT 2019
	 */
	public String getAuthorName() {
		return authorName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.tbl_book.author_name
	 * @param authorName  the value for public.tbl_book.author_name
	 * @mbg.generated  Thu Oct 31 17:03:11 ICT 2019
	 */
	public void setAuthorName(String authorName) {
		this.authorName = authorName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.tbl_book.publisher
	 * @return  the value of public.tbl_book.publisher
	 * @mbg.generated  Thu Oct 31 17:03:11 ICT 2019
	 */
	public String getPublisher() {
		return publisher;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.tbl_book.publisher
	 * @param publisher  the value for public.tbl_book.publisher
	 * @mbg.generated  Thu Oct 31 17:03:11 ICT 2019
	 */
	public void setPublisher(String publisher) {
		this.publisher = publisher;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.tbl_book.publication_day
	 * @return  the value of public.tbl_book.publication_day
	 * @mbg.generated  Thu Oct 31 17:03:11 ICT 2019
	 */
	public Date getPublicationDay() {
		return publicationDay;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.tbl_book.publication_day
	 * @param publicationDay  the value for public.tbl_book.publication_day
	 * @mbg.generated  Thu Oct 31 17:03:11 ICT 2019
	 */
	public void setPublicationDay(Date publicationDay) {
		this.publicationDay = publicationDay;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.tbl_book.regist_id
	 * @return  the value of public.tbl_book.regist_id
	 * @mbg.generated  Thu Oct 31 17:03:11 ICT 2019
	 */
	public String getRegistId() {
		return registId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.tbl_book.regist_id
	 * @param registId  the value for public.tbl_book.regist_id
	 * @mbg.generated  Thu Oct 31 17:03:11 ICT 2019
	 */
	public void setRegistId(String registId) {
		this.registId = registId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.tbl_book.regist_date
	 * @return  the value of public.tbl_book.regist_date
	 * @mbg.generated  Thu Oct 31 17:03:11 ICT 2019
	 */
	public java.util.Date getRegistDate() {
		return registDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.tbl_book.regist_date
	 * @param registDate  the value for public.tbl_book.regist_date
	 * @mbg.generated  Thu Oct 31 17:03:11 ICT 2019
	 */
	public void setRegistDate(Date registDate) {
		this.registDate = registDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.tbl_book.update_id
	 * @return  the value of public.tbl_book.update_id
	 * @mbg.generated  Thu Oct 31 17:03:11 ICT 2019
	 */
	public String getUpdateId() {
		return updateId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.tbl_book.update_id
	 * @param updateId  the value for public.tbl_book.update_id
	 * @mbg.generated  Thu Oct 31 17:03:11 ICT 2019
	 */
	public void setUpdateId(String updateId) {
		this.updateId = updateId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.tbl_book.update_date
	 * @return  the value of public.tbl_book.update_date
	 * @mbg.generated  Thu Oct 31 17:03:11 ICT 2019
	 */
	public java.util.Date getUpdateDate() {
		return updateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.tbl_book.update_date
	 * @param updateDate  the value for public.tbl_book.update_date
	 * @mbg.generated  Thu Oct 31 17:03:11 ICT 2019
	 */
	public void setUpdateDate(java.util.Date updateDate) {
		this.updateDate = updateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.tbl_book.delete_flg
	 * @return  the value of public.tbl_book.delete_flg
	 * @mbg.generated  Thu Oct 31 17:03:11 ICT 2019
	 */
	public String getDeleteFlg() {
		return deleteFlg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.tbl_book.delete_flg
	 * @param deleteFlg  the value for public.tbl_book.delete_flg
	 * @mbg.generated  Thu Oct 31 17:03:11 ICT 2019
	 */
	public void setDeleteFlg(String deleteFlg) {
		this.deleteFlg = deleteFlg;
	}
}