package com.example.orm.model;

import java.util.Date;

public class TblMember {
	

	public TblMember() {
		super();
	}

	public TblMember(String memberId, String memberFamilyName, String memberFamilyNameKana, String memberFirstName,
			String memberFirstNameKana, String address, java.sql.Date birthDay, String registId, Date registDate,
			String deleteFlg) {
		super();
		this.memberId = memberId;
		this.memberFamilyName = memberFamilyName;
		this.memberFamilyNameKana = memberFamilyNameKana;
		this.memberFirstName = memberFirstName;
		this.memberFirstNameKana = memberFirstNameKana;
		this.address = address;
		this.birthDay = birthDay;
		this.registId = registId;
		this.registDate = registDate;
		this.deleteFlg = deleteFlg;
	}

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.tbl_member.member_id
	 * @mbg.generated  Thu Oct 31 17:03:11 ICT 2019
	 */
	private String memberId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.tbl_member.member_family_name
	 * @mbg.generated  Thu Oct 31 17:03:11 ICT 2019
	 */
	private String memberFamilyName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.tbl_member.member_family_name_kana
	 * @mbg.generated  Thu Oct 31 17:03:11 ICT 2019
	 */
	private String memberFamilyNameKana;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.tbl_member.member_first_name
	 * @mbg.generated  Thu Oct 31 17:03:11 ICT 2019
	 */
	private String memberFirstName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.tbl_member.member_first_name_kana
	 * @mbg.generated  Thu Oct 31 17:03:11 ICT 2019
	 */
	private String memberFirstNameKana;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.tbl_member.address
	 * @mbg.generated  Thu Oct 31 17:03:11 ICT 2019
	 */
	private String address;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.tbl_member.birth_day
	 * @mbg.generated  Thu Oct 31 17:03:11 ICT 2019
	 */
	private java.sql.Date birthDay;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.tbl_member.regist_id
	 * @mbg.generated  Thu Oct 31 17:03:11 ICT 2019
	 */
	private String registId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.tbl_member.regist_date
	 * @mbg.generated  Thu Oct 31 17:03:11 ICT 2019
	 */
	private Date registDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.tbl_member.update_id
	 * @mbg.generated  Thu Oct 31 17:03:11 ICT 2019
	 */
	private String updateId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.tbl_member.update_date
	 * @mbg.generated  Thu Oct 31 17:03:11 ICT 2019
	 */
	private Date updateDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.tbl_member.delete_flg
	 * @mbg.generated  Thu Oct 31 17:03:11 ICT 2019
	 */
	private String deleteFlg;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.tbl_member.member_id
	 * @return  the value of public.tbl_member.member_id
	 * @mbg.generated  Thu Oct 31 17:03:11 ICT 2019
	 */
	public String getMemberId() {
		return memberId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.tbl_member.member_id
	 * @param memberId  the value for public.tbl_member.member_id
	 * @mbg.generated  Thu Oct 31 17:03:11 ICT 2019
	 */
	public void setMemberId(String memberId) {
		this.memberId = memberId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.tbl_member.member_family_name
	 * @return  the value of public.tbl_member.member_family_name
	 * @mbg.generated  Thu Oct 31 17:03:11 ICT 2019
	 */
	public String getMemberFamilyName() {
		return memberFamilyName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.tbl_member.member_family_name
	 * @param memberFamilyName  the value for public.tbl_member.member_family_name
	 * @mbg.generated  Thu Oct 31 17:03:11 ICT 2019
	 */
	public void setMemberFamilyName(String memberFamilyName) {
		this.memberFamilyName = memberFamilyName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.tbl_member.member_family_name_kana
	 * @return  the value of public.tbl_member.member_family_name_kana
	 * @mbg.generated  Thu Oct 31 17:03:11 ICT 2019
	 */
	public String getMemberFamilyNameKana() {
		return memberFamilyNameKana;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.tbl_member.member_family_name_kana
	 * @param memberFamilyNameKana  the value for public.tbl_member.member_family_name_kana
	 * @mbg.generated  Thu Oct 31 17:03:11 ICT 2019
	 */
	public void setMemberFamilyNameKana(String memberFamilyNameKana) {
		this.memberFamilyNameKana = memberFamilyNameKana;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.tbl_member.member_first_name
	 * @return  the value of public.tbl_member.member_first_name
	 * @mbg.generated  Thu Oct 31 17:03:11 ICT 2019
	 */
	public String getMemberFirstName() {
		return memberFirstName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.tbl_member.member_first_name
	 * @param memberFirstName  the value for public.tbl_member.member_first_name
	 * @mbg.generated  Thu Oct 31 17:03:11 ICT 2019
	 */
	public void setMemberFirstName(String memberFirstName) {
		this.memberFirstName = memberFirstName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.tbl_member.member_first_name_kana
	 * @return  the value of public.tbl_member.member_first_name_kana
	 * @mbg.generated  Thu Oct 31 17:03:11 ICT 2019
	 */
	public String getMemberFirstNameKana() {
		return memberFirstNameKana;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.tbl_member.member_first_name_kana
	 * @param memberFirstNameKana  the value for public.tbl_member.member_first_name_kana
	 * @mbg.generated  Thu Oct 31 17:03:11 ICT 2019
	 */
	public void setMemberFirstNameKana(String memberFirstNameKana) {
		this.memberFirstNameKana = memberFirstNameKana;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.tbl_member.address
	 * @return  the value of public.tbl_member.address
	 * @mbg.generated  Thu Oct 31 17:03:11 ICT 2019
	 */
	public String getAddress() {
		return address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.tbl_member.address
	 * @param address  the value for public.tbl_member.address
	 * @mbg.generated  Thu Oct 31 17:03:11 ICT 2019
	 */
	public void setAddress(String address) {
		this.address = address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.tbl_member.birth_day
	 * @return  the value of public.tbl_member.birth_day
	 * @mbg.generated  Thu Oct 31 17:03:11 ICT 2019
	 */
	public Date getBirthDay() {
		return birthDay;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.tbl_member.birth_day
	 * @param birthDay  the value for public.tbl_member.birth_day
	 * @mbg.generated  Thu Oct 31 17:03:11 ICT 2019
	 */
	public void setBirthDay(java.sql.Date birthDay) {
		this.birthDay = birthDay;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.tbl_member.regist_id
	 * @return  the value of public.tbl_member.regist_id
	 * @mbg.generated  Thu Oct 31 17:03:11 ICT 2019
	 */
	public String getRegistId() {
		return registId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.tbl_member.regist_id
	 * @param registId  the value for public.tbl_member.regist_id
	 * @mbg.generated  Thu Oct 31 17:03:11 ICT 2019
	 */
	public void setRegistId(String registId) {
		this.registId = registId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.tbl_member.regist_date
	 * @return  the value of public.tbl_member.regist_date
	 * @mbg.generated  Thu Oct 31 17:03:11 ICT 2019
	 */
	public Date getRegistDate() {
		return registDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.tbl_member.regist_date
	 * @param registDate  the value for public.tbl_member.regist_date
	 * @mbg.generated  Thu Oct 31 17:03:11 ICT 2019
	 */
	public void setRegistDate(Date registDate) {
		this.registDate = registDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.tbl_member.update_id
	 * @return  the value of public.tbl_member.update_id
	 * @mbg.generated  Thu Oct 31 17:03:11 ICT 2019
	 */
	public String getUpdateId() {
		return updateId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.tbl_member.update_id
	 * @param updateId  the value for public.tbl_member.update_id
	 * @mbg.generated  Thu Oct 31 17:03:11 ICT 2019
	 */
	public void setUpdateId(String updateId) {
		this.updateId = updateId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.tbl_member.update_date
	 * @return  the value of public.tbl_member.update_date
	 * @mbg.generated  Thu Oct 31 17:03:11 ICT 2019
	 */
	public Date getUpdateDate() {
		return updateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.tbl_member.update_date
	 * @param updateDate  the value for public.tbl_member.update_date
	 * @mbg.generated  Thu Oct 31 17:03:11 ICT 2019
	 */
	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.tbl_member.delete_flg
	 * @return  the value of public.tbl_member.delete_flg
	 * @mbg.generated  Thu Oct 31 17:03:11 ICT 2019
	 */
	public String getDeleteFlg() {
		return deleteFlg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.tbl_member.delete_flg
	 * @param deleteFlg  the value for public.tbl_member.delete_flg
	 * @mbg.generated  Thu Oct 31 17:03:11 ICT 2019
	 */
	public void setDeleteFlg(String deleteFlg) {
		this.deleteFlg = deleteFlg;
	}
}