package com.example.orm.model;

import java.util.Date;

public class TblRental extends TblRentalKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.tbl_rental.return_date
	 * @mbg.generated  Thu Oct 31 17:03:11 ICT 2019
	 */
	private Date returnDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.tbl_rental.status
	 * @mbg.generated  Thu Oct 31 17:03:11 ICT 2019
	 */
	private Integer status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.tbl_rental.regist_id
	 * @mbg.generated  Thu Oct 31 17:03:11 ICT 2019
	 */
	private String registId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.tbl_rental.regist_date
	 * @mbg.generated  Thu Oct 31 17:03:11 ICT 2019
	 */
	private Date registDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.tbl_rental.update_id
	 * @mbg.generated  Thu Oct 31 17:03:11 ICT 2019
	 */
	private String updateId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.tbl_rental.update_date
	 * @mbg.generated  Thu Oct 31 17:03:11 ICT 2019
	 */
	private Date updateDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.tbl_rental.delete_flg
	 * @mbg.generated  Thu Oct 31 17:03:11 ICT 2019
	 */
	private String deleteFlg;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.tbl_rental.return_date
	 * @return  the value of public.tbl_rental.return_date
	 * @mbg.generated  Thu Oct 31 17:03:11 ICT 2019
	 */
	public Date getReturnDate() {
		return returnDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.tbl_rental.return_date
	 * @param returnDate  the value for public.tbl_rental.return_date
	 * @mbg.generated  Thu Oct 31 17:03:11 ICT 2019
	 */
	public void setReturnDate(Date returnDate) {
		this.returnDate = returnDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.tbl_rental.status
	 * @return  the value of public.tbl_rental.status
	 * @mbg.generated  Thu Oct 31 17:03:11 ICT 2019
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.tbl_rental.status
	 * @param status  the value for public.tbl_rental.status
	 * @mbg.generated  Thu Oct 31 17:03:11 ICT 2019
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.tbl_rental.regist_id
	 * @return  the value of public.tbl_rental.regist_id
	 * @mbg.generated  Thu Oct 31 17:03:11 ICT 2019
	 */
	public String getRegistId() {
		return registId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.tbl_rental.regist_id
	 * @param registId  the value for public.tbl_rental.regist_id
	 * @mbg.generated  Thu Oct 31 17:03:11 ICT 2019
	 */
	public void setRegistId(String registId) {
		this.registId = registId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.tbl_rental.regist_date
	 * @return  the value of public.tbl_rental.regist_date
	 * @mbg.generated  Thu Oct 31 17:03:11 ICT 2019
	 */
	public Date getRegistDate() {
		return registDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.tbl_rental.regist_date
	 * @param registDate  the value for public.tbl_rental.regist_date
	 * @mbg.generated  Thu Oct 31 17:03:11 ICT 2019
	 */
	public void setRegistDate(Date registDate) {
		this.registDate = registDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.tbl_rental.update_id
	 * @return  the value of public.tbl_rental.update_id
	 * @mbg.generated  Thu Oct 31 17:03:11 ICT 2019
	 */
	public String getUpdateId() {
		return updateId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.tbl_rental.update_id
	 * @param updateId  the value for public.tbl_rental.update_id
	 * @mbg.generated  Thu Oct 31 17:03:11 ICT 2019
	 */
	public void setUpdateId(String updateId) {
		this.updateId = updateId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.tbl_rental.update_date
	 * @return  the value of public.tbl_rental.update_date
	 * @mbg.generated  Thu Oct 31 17:03:11 ICT 2019
	 */
	public Date getUpdateDate() {
		return updateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.tbl_rental.update_date
	 * @param updateDate  the value for public.tbl_rental.update_date
	 * @mbg.generated  Thu Oct 31 17:03:11 ICT 2019
	 */
	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.tbl_rental.delete_flg
	 * @return  the value of public.tbl_rental.delete_flg
	 * @mbg.generated  Thu Oct 31 17:03:11 ICT 2019
	 */
	public String getDeleteFlg() {
		return deleteFlg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.tbl_rental.delete_flg
	 * @param deleteFlg  the value for public.tbl_rental.delete_flg
	 * @mbg.generated  Thu Oct 31 17:03:11 ICT 2019
	 */
	public void setDeleteFlg(String deleteFlg) {
		this.deleteFlg = deleteFlg;
	}
}