package com.example.orm.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import com.example.orm.model.TblAdmin;
import com.example.orm.model.TblAdminExample;

@Mapper
public interface TblAdminMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tbl_admin
	 * @mbg.generated  Thu Oct 31 17:03:11 ICT 2019
	 */
	long countByExample(TblAdminExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tbl_admin
	 * @mbg.generated  Thu Oct 31 17:03:11 ICT 2019
	 */
	int deleteByExample(TblAdminExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tbl_admin
	 * @mbg.generated  Thu Oct 31 17:03:11 ICT 2019
	 */
	int deleteByPrimaryKey(String adminId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tbl_admin
	 * @mbg.generated  Thu Oct 31 17:03:11 ICT 2019
	 */
	int insert(TblAdmin record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tbl_admin
	 * @mbg.generated  Thu Oct 31 17:03:11 ICT 2019
	 */
	int insertSelective(TblAdmin record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tbl_admin
	 * @mbg.generated  Thu Oct 31 17:03:11 ICT 2019
	 */
	List<TblAdmin> selectByExample(TblAdminExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tbl_admin
	 * @mbg.generated  Thu Oct 31 17:03:11 ICT 2019
	 */
	TblAdmin selectByPrimaryKey(String adminId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tbl_admin
	 * @mbg.generated  Thu Oct 31 17:03:11 ICT 2019
	 */
	int updateByExampleSelective(@Param("record") TblAdmin record, @Param("example") TblAdminExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tbl_admin
	 * @mbg.generated  Thu Oct 31 17:03:11 ICT 2019
	 */
	int updateByExample(@Param("record") TblAdmin record, @Param("example") TblAdminExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tbl_admin
	 * @mbg.generated  Thu Oct 31 17:03:11 ICT 2019
	 */
	int updateByPrimaryKeySelective(TblAdmin record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tbl_admin
	 * @mbg.generated  Thu Oct 31 17:03:11 ICT 2019
	 */
	int updateByPrimaryKey(TblAdmin record);
}