package com.example.orm.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

import com.example.orm.model.TblMember;
import com.example.orm.model.TblMemberExample;

@Mapper
public interface TblMemberMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tbl_member
	 * @mbg.generated  Thu Oct 31 17:03:11 ICT 2019
	 */
	long countByExample(TblMemberExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tbl_member
	 * @mbg.generated  Thu Oct 31 17:03:11 ICT 2019
	 */
	int deleteByExample(TblMemberExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tbl_member
	 * @mbg.generated  Thu Oct 31 17:03:11 ICT 2019
	 */
	int deleteByPrimaryKey(String memberId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tbl_member
	 * @mbg.generated  Thu Oct 31 17:03:11 ICT 2019
	 */
	int insert(TblMember record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tbl_member
	 * @mbg.generated  Thu Oct 31 17:03:11 ICT 2019
	 */
	int insertSelective(TblMember record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tbl_member
	 * @mbg.generated  Thu Oct 31 17:03:11 ICT 2019
	 */
	List<TblMember> selectByExample(TblMemberExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tbl_member
	 * @mbg.generated  Thu Oct 31 17:03:11 ICT 2019
	 */
	TblMember selectByPrimaryKey(String memberId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tbl_member
	 * @mbg.generated  Thu Oct 31 17:03:11 ICT 2019
	 */
	int updateByExampleSelective(@Param("record") TblMember record, @Param("example") TblMemberExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tbl_member
	 * @mbg.generated  Thu Oct 31 17:03:11 ICT 2019
	 */
	int updateByExample(@Param("record") TblMember record, @Param("example") TblMemberExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tbl_member
	 * @mbg.generated  Thu Oct 31 17:03:11 ICT 2019
	 */
	int updateByPrimaryKeySelective(TblMember record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tbl_member
	 * @mbg.generated  Thu Oct 31 17:03:11 ICT 2019
	 */
	int updateByPrimaryKey(TblMember record);

	@Select("SELECT * FROM tbl_member")
	List<TblMember> getAll();
}