package com.example.orm.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import com.example.orm.model.TblRental;
import com.example.orm.model.TblRentalExample;
import com.example.orm.model.TblRentalKey;

@Mapper
public interface TblRentalMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tbl_rental
	 * @mbg.generated  Thu Oct 31 17:03:11 ICT 2019
	 */
	long countByExample(TblRentalExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tbl_rental
	 * @mbg.generated  Thu Oct 31 17:03:11 ICT 2019
	 */
	int deleteByExample(TblRentalExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tbl_rental
	 * @mbg.generated  Thu Oct 31 17:03:11 ICT 2019
	 */
	int deleteByPrimaryKey(TblRentalKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tbl_rental
	 * @mbg.generated  Thu Oct 31 17:03:11 ICT 2019
	 */
	int insert(TblRental record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tbl_rental
	 * @mbg.generated  Thu Oct 31 17:03:11 ICT 2019
	 */
	int insertSelective(TblRental record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tbl_rental
	 * @mbg.generated  Thu Oct 31 17:03:11 ICT 2019
	 */
	List<TblRental> selectByExample(TblRentalExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tbl_rental
	 * @mbg.generated  Thu Oct 31 17:03:11 ICT 2019
	 */
	TblRental selectByPrimaryKey(TblRentalKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tbl_rental
	 * @mbg.generated  Thu Oct 31 17:03:11 ICT 2019
	 */
	int updateByExampleSelective(@Param("record") TblRental record, @Param("example") TblRentalExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tbl_rental
	 * @mbg.generated  Thu Oct 31 17:03:11 ICT 2019
	 */
	int updateByExample(@Param("record") TblRental record, @Param("example") TblRentalExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tbl_rental
	 * @mbg.generated  Thu Oct 31 17:03:11 ICT 2019
	 */
	int updateByPrimaryKeySelective(TblRental record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tbl_rental
	 * @mbg.generated  Thu Oct 31 17:03:11 ICT 2019
	 */
	int updateByPrimaryKey(TblRental record);
}